title: LezWatch Documentation
description: How to be the greatest database ever.
remote_theme: "mmistakes/minimal-mistakes"
avatar: https://lezwatch.github.io/assets/images/lwtv-logo.png

timezone: America/New_York

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: https://twitter.com/lezwatchtv
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: https://www.facebook.com/lezwatchtv/
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: https://github.com/lezwatch/
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: https://www.instagram.com/lezwatchtv/
    - label: "Tumblr"
      icon: "fab fa-fw fa-tumblr"
      url: https://lezwatchtv.tumblr.com/

# Reading Files
include:
  - _administration
  - _writing
  - _pages

defaults:
  # Everything
  - scope:
      path: ""
    values:
      layout: single

# Includes an icon in the footer for each username you enter
footer-links:
  email: contact@lezwatchtv.com
  facebook: lezwatchtv
  github: lezwatch
  instagram: lezwatchtv
  twitter: lezwatchtv

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
